# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

image: gmacario/build-yocto:latest

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python-git
   
build1:
  stage: build
  script:
    - git clone -b thud git://git.yoctoproject.org/poky
    - git clone -b thud git://github.com/Xilinx/meta-xilinx
    - git clone -b thud git://github.com/ovpanait/meta-artyz7
    - . poky/oe-init-build-env
    - bitbake-layers add-layer ../meta-xilinx/meta-xilinx-bsp/
    - bitbake-layers add-layer ../meta-artyz7
    - echo 'MACHINE="arty-zynq7"' >> conf/local.conf
    - bitbake core-image-minimal
