# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

image: gmacario/build-yocto:latest

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python-git
   
build1:
  stage: build
  script:
    - git clone -b master git://git.yoctoproject.org/poky
    # Needed by meta-xilinx-bsp
    - git clone -b master https://github.com/openembedded/meta-openembedded.git
    # The master branch of meta-xilinx is broken for now, master-next is the updated one
    - git clone -b master-next git://github.com/Xilinx/meta-xilinx
    - git clone -b master git://github.com/ovpanait/meta-artyz7
    - . poky/oe-init-build-env
    - bitbake-layers add-layer ../meta-openembedded/meta-oe/
    - echo 'LAYERSERIES_COMPAT_xilinx += "warrior"' >> ../meta-xilinx/meta-xilinx-bsp/conf/layer.conf
    - bitbake-layers add-layer ../meta-xilinx/meta-xilinx-bsp/
    - bitbake-layers add-layer ../meta-artyz7
    - echo 'INHERIT += "rm_work"' >> conf/local.conf
    - echo 'MACHINE="arty-zynq7"' >> conf/local.conf
    - bitbake core-image-minimal
